# Generated by Django 2.2.10 on 2021-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('color', models.IntegerField(default=0)),
                ('wNews', models.IntegerField(default=0)),
                ('wStock', models.IntegerField(default=0)),
                ('wWeather', models.IntegerField(default=0)),
                ('wMail', models.IntegerField(default=0)),
                ('wCalendar', models.IntegerField(default=0)),
            ],
        ),
    ]
